# Generated by Django 4.2.5 on 2023-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images"
            ),
        ),
    ]
